<#
  Installs the two user-facing pieces of the dev server:

    1. a logon scheduled task that starts driver.mjs with no visible window
    2. a "Vibe Kanban" desktop shortcut that opens the board (starting the
       server first only if it is not already up)

  Everything it generates lives in ~\.vibe-kanban\launcher, so a deleted git
  worktree cannot break the installed shortcut. Re-run after pulling changes to
  open.mjs. No elevation required.

  Usage:  powershell -ExecutionPolicy Bypass -File install-autostart.ps1 [-RepoRoot C:\lab\vibe-kanban]
#>
[CmdletBinding()]
param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,
  [string]$InstallDir = (Join-Path $env:USERPROFILE '.vibe-kanban\launcher'),
  [string]$TaskName = 'VibeKanbanDev',
  [string]$ShortcutName = 'Vibe Kanban'
)

$ErrorActionPreference = 'Stop'

$RepoRoot = (Resolve-Path $RepoRoot).Path
$driver = Join-Path $RepoRoot '.claude\skills\run-vibe-kanban\driver.mjs'
if (-not (Test-Path $driver)) { throw "driver.mjs not found under $RepoRoot" }

$home_ = $InstallDir
New-Item -ItemType Directory -Force -Path $home_ | Out-Null
$home_ = (Resolve-Path $home_).Path

$openMjs      = Join-Path $home_ 'open.mjs'
$driverMjs    = Join-Path $home_ 'driver.mjs'
$autostartVbs = Join-Path $home_ 'autostart.vbs'
$openVbs      = Join-Path $home_ 'open.vbs'
$icon         = Join-Path $home_ 'vk.ico'
# Copies, not references into the repo: the installed launcher must survive a
# branch switch or a deleted worktree. Both honour VK_ROOT / --root.
Copy-Item (Join-Path $PSScriptRoot 'open.mjs') $openMjs -Force
Copy-Item (Join-Path $PSScriptRoot 'driver.mjs') $driverMjs -Force

# --- hidden launchers -------------------------------------------------------
# WScript.Shell.Run with windowStyle 0 is the only reliable way to get a truly
# invisible console on Windows: Task Scheduler's "hidden" still flashes conhost,
# and every child (cargo-watch, vite) inherits this hidden console.
$autostartLog = Join-Path $home_ 'autostart.log'
$openLog      = Join-Path $home_ 'open.log'

@"
' Generated by install-autostart.ps1 - starts the vibe-kanban dev server, no window.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$RepoRoot"
sh.Run "cmd /c node ""$openMjs"" --root ""$RepoRoot"" --log-dir ""$home_"" --no-open >> ""$autostartLog"" 2>&1", 0, False
"@ | Set-Content -Path $autostartVbs -Encoding ASCII

@"
' Generated by install-autostart.ps1 - opens the board, starting the server only if needed.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$RepoRoot"
sh.Run "cmd /c node ""$openMjs"" --root ""$RepoRoot"" --log-dir ""$home_"" >> ""$openLog"" 2>&1", 0, False
"@ | Set-Content -Path $openVbs -Encoding ASCII

# --- icon -------------------------------------------------------------------
# 256px 32bpp BMP payload, not PNG: PNG-compressed .ico entries are legal since
# Vista but System.Drawing (and some shell extensions) cannot decode them, which
# makes the icon unverifiable and occasionally blank.
Add-Type -AssemblyName System.Drawing
$size = 256
$bmp = New-Object System.Drawing.Bitmap $size, $size
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.SmoothingMode = 'AntiAlias'
$g.TextRenderingHint = 'AntiAliasGridFit'
$r = 56
$p = New-Object System.Drawing.Drawing2D.GraphicsPath
$p.AddArc(0, 0, $r, $r, 180, 90)
$p.AddArc($size - $r, 0, $r, $r, 270, 90)
$p.AddArc($size - $r, $size - $r, $r, $r, 0, 90)
$p.AddArc(0, $size - $r, $r, $r, 90, 90)
$p.CloseFigure()
$g.FillPath((New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(255, 12, 16, 28))), $p)
$font = New-Object System.Drawing.Font 'Segoe UI', 104, ([System.Drawing.FontStyle]::Bold), ([System.Drawing.GraphicsUnit]::Pixel)
$fmt = New-Object System.Drawing.StringFormat
$fmt.Alignment = 'Center'; $fmt.LineAlignment = 'Center'
$g.DrawString('VK', $font, [System.Drawing.Brushes]::White, (New-Object System.Drawing.RectangleF 0, 0, $size, $size), $fmt)
$g.Dispose()

$rect = New-Object System.Drawing.Rectangle 0, 0, $size, $size
$locked = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$pixels = New-Object byte[] ($size * $size * 4)
[System.Runtime.InteropServices.Marshal]::Copy($locked.Scan0, $pixels, 0, $pixels.Length)
$bmp.UnlockBits($locked)
$bmp.Dispose()

$dibBytes = 40 + $pixels.Length + ($size * $size / 8)
$ico = New-Object System.IO.MemoryStream
$w = New-Object System.IO.BinaryWriter $ico
$w.Write([uint16]0); $w.Write([uint16]1); $w.Write([uint16]1)   # reserved, type=icon, 1 image
$w.Write([byte]0); $w.Write([byte]0)                            # 0 = 256px
$w.Write([byte]0); $w.Write([byte]0)                            # palette, reserved
$w.Write([uint16]1); $w.Write([uint16]32)                       # planes, bpp
$w.Write([uint32]$dibBytes); $w.Write([uint32]22)               # payload size, offset
$w.Write([uint32]40); $w.Write([int32]$size); $w.Write([int32]($size * 2))  # BITMAPINFOHEADER: height is doubled (XOR + AND masks)
$w.Write([uint16]1); $w.Write([uint16]32)
$w.Write([uint32]0); $w.Write([uint32]$pixels.Length)
$w.Write([uint32]0); $w.Write([uint32]0); $w.Write([uint32]0); $w.Write([uint32]0)
for ($y = $size - 1; $y -ge 0; $y--) { $w.Write($pixels, $y * $size * 4, $size * 4) }  # DIB rows are bottom-up
$w.Write((New-Object byte[] ($size * $size / 8)))               # AND mask: unused, alpha carries it
$w.Flush()
[System.IO.File]::WriteAllBytes($icon, $ico.ToArray())
$w.Dispose()

# --- desktop shortcut -------------------------------------------------------
$lnk = Join-Path ([Environment]::GetFolderPath('Desktop')) "$ShortcutName.lnk"
$sc = (New-Object -ComObject WScript.Shell).CreateShortcut($lnk)
$sc.TargetPath = Join-Path $env:WINDIR 'System32\wscript.exe'
$sc.Arguments = "//nologo `"$openVbs`""
$sc.WorkingDirectory = $RepoRoot
$sc.IconLocation = "$icon,0"
$sc.Description = 'Open the Vibe Kanban board (starts the dev server if needed)'
$sc.Save()

# --- logon task -------------------------------------------------------------
# Scheduled task over shell:startup: it survives startup-folder policies, can be
# delayed off the boot storm, and restarts itself if the dev server dies.
$action = New-ScheduledTaskAction -Execute (Join-Path $env:WINDIR 'System32\wscript.exe') `
  -Argument "//nologo `"$autostartVbs`"" -WorkingDirectory $RepoRoot
$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"
$trigger.Delay = 'PT1M'
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -StartWhenAvailable -MultipleInstances IgnoreNew -ExecutionTimeLimit ([TimeSpan]::Zero) `
  -RestartCount 2 -RestartInterval (New-TimeSpan -Minutes 5)
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings `
  -Principal $principal -Description 'Starts the vibe-kanban dev server at logon (hidden).' -Force | Out-Null

Write-Host "installed:"
Write-Host "  task      $TaskName (at logon, +1 min, hidden)"
Write-Host "  shortcut  $lnk"
Write-Host "  launchers $autostartVbs"
Write-Host "            $openVbs"
Write-Host "  icon      $icon"
Write-Host "  logs      $autostartLog | $openLog | $(Join-Path $home_ 'vk-server.log')"
Write-Host "  repo      $RepoRoot"
